### ISSUE TITLE
document/element queries

### ISSUE THREAD

**Issue by pakastin** [pakastin/nodom#1]
- [ ] document.getElementById
- [ ] document.querySelector
- [ ] document.querySelectorAll
- [ ] document.getElementsByClassName
- [x] document.getElementsByTagName
- [ ] document.getElementsByTagNameNS

- [ ] element.querySelector
- [ ] element.querySelectorAll
- [ ] element.getElementsByClassName
- [x] element.getElementsByTagName
- [ ] element.getElementsByTagNameNS

**Comment by nikcorg** [comment]
Should be all done, save for the NS-versions.
